version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  db-filler:
    build:  
      context: ./database-filler
      args:
        - DATA_PATH=/data
    volumes:
      - ./data:/data 
    depends_on:
      - db
    restart: on-failure:10
  server:
    build:
      ./server
    ports:
      - "5000:5000"
volumes:
  data: {}
